blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/like/', views.like_post, name='like_post'),
    path('post/<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('blog_page/', views.blog_page, name='blog_page'),
]

movies/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movie_media/', include('movie_media.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('subscriber/', include('subscriber.urls')),
    path('about/', include('about.urls')),
    path('series/', include('series.urls')),
    path('contact/', include('contact.urls')),
    path('', home, name='home'),
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='blog/images/', null=True, blank=True)

    def __str__(self):
        return self.title

    @property
    def likes_count(self):
        return self.likes.count()

    @property
    def comments_count(self):
        return self.comments.count()

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.post}'

class Like(models.Model):
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Like by {self.user} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, Like
from django.contrib.auth.decorators import login_required
from .forms import CommentForm
from django.views.generic import ListView, DetailView
from .models import Post, Comment, Like

def post_list(request):
    posts = Post.objects.all().order_by('-created_at')
    return render(request, 'blog/post_list.html', {'posts': posts})

@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    is_liked = post.likes.filter(user=request.user).exists()
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('blog:post_detail', post_id=post.id)
    else:
        form = CommentForm()
    
    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'form': form, 'is_liked': is_liked})

class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'latest_posts'
    ordering = ['-created_at']

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

@login_required
def like_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    like, created = Like.objects.get_or_create(user=request.user, post=post)
    if not created:
        like.delete()
    return redirect('blog:post_detail', pk=pk)

@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            # Update comments queryset after saving new comment
            comments = post.comments.all()
            return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'form': form})
    else:
        form = CommentForm()
    
    # Fetch comments for the post before adding a new comment
    comments = post.comments.all()
    
    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'form': form})


def blog_page(request):
    latest_posts = Post.objects.order_by('-created_at')[:5]
    random_comments = Comment.objects.order_by('?')[:5]


    context = {'latest_posts': latest_posts,'random_comments': random_comments,}
    return render(request, 'home.html', context)
   

blog/templates/blog/add_comment.html
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Comment</button>
</form>

blog/templates/blog/blog_page.html
{% extends 'base.html' %}
{% block content %}

<section id="center" class="center_o pt-5">
    <div class="container">
        <div class="row center_o1 text-center">
            <div class="col-md-12">
                <h2>BLOG CATEGORIES</h2>
                <h5 class="bg_dark d-inline-block p-4 mb-0 mt-4 pt-2 pb-2 fw-normal col_red">
                    <a class="text-white" href="{% url 'home' %}">Home</a>
                    <span class="me-2 ms-2 text-muted"> /</span> Blog
                </h5>
            </div>
        </div>
    </div>
</section>

<section id="blog" class="p_3 bg-light">
    <div class="container">
        <div class="row blog1">
            <div class="col-md-9">
                <div class="blog1l">
                    {% for post in latest_posts %}
                        <div class="blog1l1 bg-white mt-4">
                            <div class="grid clearfix">
                                <figure class="effect-jazz mb-0">
                                    <a href="{% url 'blog:post_detail' post.pk %}">
                                        <img src="{{ post.image.url }}" height="480" class="w-100" alt="{{ post.title }}">
                                    </a>
                                </figure>
                            </div>
                            <div class="blog1l1i clearfix p-4">
                                <h6 class="col_red">{{ post.created_at|date:"d M Y" }} <span class="me-2 ms-2">|</span> by {{ post.author.username }}</h6>
                                <h4 class="mt-3">
                                    <a href="{% url 'blog:post_detail' post.pk %}">
                                        {{ post.title }}
                                    </a>
                                </h4>
                                <p>{{ post.content|truncatewords:30 }}</p>
                                <h6 class="mb-0">
                                    <a class="button_1" href="{% url 'blog:post_detail' post.pk %}">Read More <i class="fa fa-long-arrow-right ms-1"></i></a>
                                </h6>
                            </div>
                            <div class="blog1l1i1 clearfix row m-0 p-3">
                                <div class="col-md-9">
                                    <div class="blog1l1i1l">
                                        <ul class="mb-0">
                                            <li class="d-inline-block col_red me-3">
                                                <i class="fa fa-thumbs-up me-1"></i> 
                                                <a href="{% url 'blog:like_post' post.pk %}">{{ post.likes_count }} Likes</a>
                                            </li>
                                            <li class="d-inline-block col_red me-3">
                                                <i class="fa fa-comments me-1"></i>
                                                <a href="{% url 'blog:post_detail' post.pk %}#comments">{{ post.comments_count }} Comments</a>
                                            </li>
                                            <li class="d-inline-block col_red">
                                                <i class="fa fa-tags me-1"></i>
                                                <a href="{% url 'blog:post_detail' post.pk %}">{{ post.category.name }}</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="blog1l1i1r text-end">
                                        <ul class="mb-0">
                                            <li class="d-inline-block me-2">
                                                <a href="#"><i class="fa fa-facebook"></i></a>
                                            </li>
                                            <li class="d-inline-block me-2">
                                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                                            </li>
                                            <li class="d-inline-block me-2">
                                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                            </li>
                                            <li class="d-inline-block">
                                                <a href="#"><i class="fa fa-twitter"></i></a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/post_detail.html
<!-- post_detail.html -->

{% extends 'base.html' %}
{% block content %}

<section id="post-detail" class="p-3 bg-light">
    <div class="container-xl">
        <div class="row">
            <!-- Left column for post content -->
            <div class="col-lg-8">
                <div class="post-content">
                    <h2>{{ post.title }}</h2>
                    <img src="{{ post.image.url }}" class="img-fluid mb-3" alt="{{ post.title }}">
                    <p>{{ post.content }}</p>
                    <hr>
                    <!-- Display comments -->
                    <div id="comments">
                        <h3>Comments ({{ comments.count }})</h3>
                        <ul class="list-unstyled">
                            {% for comment in comments %}
                                <li class="mb-4">
                                    <div class="comment">
                                        <p>{{ comment.content }}</p>
                                        <p class="text-muted">By {{ comment.author.username }} on {{ comment.created_at|date:"d M Y" }}</p>
                                    </div>
                                </li>
                            {% empty %}
                                <li>No comments yet.</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Right column for comment form -->
            <div class="col-lg-4 mt-4 mt-lg-0">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Add a Comment</h3>
                        <form method="post" action="{% url 'blog:add_comment' post.pk %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary mt-3">Submit</button>
                        </form>
                    </div>
                </div>
            </div>            
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Blog Posts</h1>
{% for post in posts %}
    <h2><a href="{% url 'post_detail' post.id %}">{{ post.title }}</a></h2>
    <p>{{ post.content|truncatewords:30 }}</p>
{% endfor %}
{% endblock %}